arch:
    - amd64
    - ppc64le
language: java
sudo: required

jdk:
- openjdk11
# - oraclejdk8
# `openjdk8` not available

install:
# download models (see `README.md`)
- wget http://nlp.stanford.edu/software/stanford-corenlp-models-current.jar
- wget http://nlp.stanford.edu/software/stanford-english-corenlp-models-current.jar
- mvn install:install-file -Dfile=stanford-corenlp-models-current.jar -DgroupId=edu.stanford.nlp -DartifactId=stanford-corenlp -Dversion=4.2.0 -Dclassifier=models -Dpackaging=jar
- mvn install:install-file -Dfile=stanford-english-corenlp-models-current.jar -DgroupId=edu.stanford.nlp -DartifactId=stanford-corenlp -Dversion=4.2.0 -Dclassifier=models-english -Dpackaging=jar

- mv stanford-corenlp-models-current.jar stanford-corenlp-4.2.0-models.jar
# necessary for `mvn install`
after_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "ppc64le" ]]; then
  	 apt update
	 apt install ant
	 ant -version
    fi

script:
- ant
- ./gradlew
- mvn install

#blocklist
branches:
  except:
  - gh-pages
